language: python
cache: pip
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - sudo apt-get install libav-tools python-dbus python3-dbus
  - pip install -r requirements.txt
# command to run tests
script:
  - coverage run setup.py test
  - codecov
